# config/colors.yaml
method_colors:
  LouvainSigned_default:  "#56B4E9"   # Blue for default
  LouvainSigned_tuned:    "#005A9C"   # Darker blue for tuned
  Louvain:                "#E69F00"   # Orange
  Leiden:                 "#009E73"   # Green
  Greedy:                 "#D55E00"   # Vermilion
  Spinglass:              "#CC79A7"   # Reddish purple
  Walktrap:               "#78f5ae"   # Light-green
  LPA:                    "#F0E42A"   # Yellow-green